# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '/home/vsts/work/1/s'
    Contents: '**'
    TargetFolder: '/home/vsts/work/1/a'

- task: DeleteFiles@1
  inputs:
    SourceFolder: '/home/vsts/work/1/a'
    Contents: '.git'
    RemoveSourceFolder: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '/home/vsts/work/1/a'
    ArtifactName: 'drop'
    publishLocation: 'Container'