version: '3'
services:

  api:
    build:  
      context: api/.
    image: api
    container_name: api
    ports:
      - "3000:3000"
    restart: always

  backend:
    build:  
      context: backend/.
    image: backend
    container_name: backend
    ports:
      - "4000:4000"
    restart: always

  node:
    build:  
      context: node/.
    image: node 
    container_name: node
    ports:
      - "5000:5000"
    restart: always
    
